server.forward-headers-strategy=native
server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=2h
server.compression.enabled=true
server.shutdown=graceful
spring.application.name=Alf.io
logging.level.root=warn
logging.level.alfio=info

# ===================================================================
# Apple OAuth2 Login Configuration
# ===================================================================
# Enable by providing a client-id
spring.security.oauth2.client.registration.apple.client-id=[Your Service ID]
spring.security.oauth2.client.registration.apple.client-secret=not-used # Will be generated dynamically
spring.security.oauth2.client.registration.apple.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.apple.scope=name,email
spring.security.oauth2.client.registration.apple.team-id=[Your Apple Team ID]
spring.security.oauth2.client.registration.apple.key-id=[Your Key ID]
# The private key should be in a single line. In .properties files, you can use a backslash to continue a line.
spring.security.oauth2.client.registration.apple.private-key=-----BEGIN PRIVATE KEY-----\n[YOUR_PRIVATE_KEY_CONTENT_IN_ONE_LINE]\n-----END PRIVATE KEY-----

spring.security.oauth2.client.provider.apple.authorization-uri=https://appleid.apple.com/auth/authorize
spring.security.oauth2.client.provider.apple.token-uri=https://appleid.apple.com/auth/token
spring.security.oauth2.client.provider.apple.jwk-set-uri=https://appleid.apple.com/auth/keys
spring.security.oauth2.client.provider.apple.issuer-uri=https://appleid.apple.com
spring.security.oauth2.client.provider.apple.user-name-attribute=sub

